kind = "mobile"
previewPath = "/safepark-mobile/"
title = "SafePark Operador"
version = "1.0.0"
id = "artifacts/safepark-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/safepark-mobile/" ]
localPort = 25775

[services.development]
run = "pnpm --filter @workspace/safepark-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/safepark-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/safepark-mobile", "run", "serve" ]

[services.env]
PORT = "25775"
BASE_PATH = "/safepark-mobile/"
